name: Vercel Deploy

on:
  push:
    branches:
      - dev

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            echo "Error: VERCEL_DEPLOY_HOOK secret is not set."
            exit 1
          fi
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
